### ISSUE TITLE
twiceMonthly resulting cron

### ISSUE THREAD

**Issue by jmcguire81** [dragonmantank/cron-expression#101]
Hi,
I noticed that the resulting cron expression from twiceMonthly()  always has an hour & minute at 0, ignoring the time passed. I believe this resolves the issue:

Before:
`public function twiceMonthly($first = 1, $second = 16, $time = '0:0')
    {
        $daysOfMonth = $first.','.$second;

        $this->dailyAt($time);

        return $this->spliceIntoPosition(1, 0)
            ->spliceIntoPosition(2, 0)
            ->spliceIntoPosition(3, $daysOfMonth);
    }`

After:
`public function twiceMonthly($first = 1, $second = 16, $time = '0:0')
    {
        $daysOfMonth = $first.','.$second;

        $this->dailyAt($time);

        return $this->spliceIntoPosition(3, $daysOfMonth);
    }`

**Comment by dragonmantank** [comment]
Hello!

I am not sure what code this is referring to. This library doesn't have a `twiceMonthly()` method on any of the objects, so I'm not quite sure what I can do to help. 

Feel free to re-open if you have any more information.

**Comment by jmcguire81** [comment]
Hello,
My mistake, this bug was actually in a task scheduling library in Larvel. I
was reviewing your library for processing the resulting cron statements and
must have inadvertently submitted the bug to the wrong project. Sorry for
the confusion

John
