### ISSUE TITLE
composer require dragonmantank/cron-expression for laravel v6.18.35

### ISSUE THREAD

**Issue by Volodymyr-Resqdev** [dragonmantank/cron-expression#103]
Hello

There is no way to install the package into Laravel 6. In composer.json file I using larave version like this - "laravel/framework": "^6". I got this error messages:
 
Problem 1
    - Installation request for dragonmantank/cron-expression ^3.0 -> satisfiable by dragonmantank/cron-expression[3.0.1, v3.0.0, v3.0.2].
    - laravel/framework v6.18.35 requires dragonmantank/cron-expression ^2.0 -> satisfiable by dragonmantank/cron-expression[v2.3.1.x-dev].
    - laravel/framework v6.18.35 requires dragonmantank/cron-expression ^2.0 -> satisfiable by dragonmantank/cron-expression[v2.3.1.x-dev].
    - laravel/framework v6.18.35 requires dragonmantank/cron-expression ^2.0 -> satisfiable by dragonmantank/cron-expression[v2.3.1.x-dev].
    - Conclusion: don't install dragonmantank/cron-expression v2.3.1.x-dev
    - Installation request for laravel/framework (locked at v6.18.35, required as ^6) -> satisfiable by laravel/framework[v6.18.35].

**Comment by dragonmantank** [comment]
This library is already bundled with `laravel/framework`, and Laravel 6 is locked to the 2.3.x branch of this library. Unfortunately, without updating your version of Laravel to a newer version you are restricted to what they allow. 

Sorry :(
