### ISSUE TITLE
getPreviousRunDate doesn't return the right job if it was at the same minute

### ISSUE THREAD

**Issue by Adrriii** [dragonmantank/cron-expression#109]
I encounter this bug with a job of `*/12 * * * *`

If it's 00:10:00, the previous job is at 00:00:00 and the next at 00:12:00
If it's 00:15:00, the previous job is at 00:12:00 and the next at 00:24:00

But if it's somewhere at 00:12:xx, the results are 00:00:00 and 00:24:00
If don't know if this is expected behavior, but in my case it wasn't, I expected getPreviousJob to return the job that started seconds ago, not the older one.

**Comment by dragonmantank** [comment]
This is technically correct. Cron jobs are granular only to the minute, not to the second, the previous run would be 12 minutes before, and next run is 12 minutes later. Seconds are effectively ignored.

**Comment by Adrriii** [comment]
It might be a good feature to add something along the lines of "isRunning()" or "isNow()" to be able to handle this edge case then ?

In my code I had to find a workaround that sadly makes the script dependant of the cron formula by more than its expression, which would've been the goal of this dependency. The issue for me is temporarily resolved for me anyway.

**Comment by dragonmantank** [comment]
Closing this. You would need much more infrastructure to know if an existing command is running (which gets into job running, which is above-and-beyond the scope of this library), and as mentioned cron is only ever granular to the minute.
