### ISSUE TITLE
Unable to validate a cron expression for some case

### ISSUE THREAD

**Issue by Akashgkv** [dragonmantank/cron-expression#110]
I use this cron expression 0 0 1 1/1 * it's a correct cron expression but it throws invalid. can you help me

**Comment by Akashgkv** [comment]
In a cron expression with / character  is not taken has a valid expression

**Comment by dragonmantank** [comment]
You cannot have a range of a single value with a step. `1/1` is invalid as it semantically does not make sense as it translates to `A range of 1, step 1` ... you would just want a simple `1` for the value, or `*` if you intend for it to run all the time.
