### ISSUE TITLE
Quarterly Cron Expression

### ISSUE THREAD

**Issue by ericmg97** [dragonmantank/cron-expression#116]
This cron expression must execute on 1st of January, April, July and October.

``` PHP
$cron = new CronExpression::factory('0 0 1 */3 *');
```

But it executes on 1st of March, June, September and December:

``` PHP
echo $cron->getNextRunDate()->format('Y-m-d H:i:s');
```
Output:
``` Console
2021-09-01 00:00:00
```

**Comment by tomme87** [comment]
I have the same issue with every 4th month (tertial) (ie. `30 2 2 1/4 *`)

**Comment by bilogic** [comment]
@ericmg97 which version are you using? This seems to have been fixed years ago https://github.com/laravel/framework/issues/19532

**Comment by dragonmantank** [comment]
Yes, please let me know what version you are using. This was the actual original impetus for v2 (there were so many people who relied on the bad behavior it still exists in v1). Feel free to re-open if you are using v3.
