### ISSUE TITLE
Value 00 is treated as invalid

### ISSUE THREAD

**Issue by jakub-klapka** [dragonmantank/cron-expression#12]
Hello,
in new versions, literal '00' as part of cron expression is now treated as invalid. This was not the case in previous versions.
It's probably due to php filter behaviour, where in AbstractField.php, line 261:
`filter_var($value, FILTER_VALIDATE_INT)` returns false for '00' but returns 0 for '0'.

The same applies for other strings like '05' etc,

Thanks for cheking that, Jakub

**Comment by fawzib** [comment]
true that. i had to update my cron expressions

**Comment by dragonmantank** [comment]
Verified that cronie allows leading 0s in it's format, and it does.

Corrected this with https://github.com/dragonmantank/cron-expression/commit/d403cc2a530a1b1c0ef2fdec7299121cec9c6ab6

Thank you!
