### ISSUE TITLE
getNextRunDate fails with this expression '0 0 1-7 * 1'

### ISSUE THREAD

**Issue by RebafC** [dragonmantank/cron-expression#123]
I understand the '0 0 1-7 * 1' expression to mean "At 12:00am on the 1st through 7th on Monday".  The test below fails with this description "2021-09-06 00:00:00  !== 2021-08-30 00:00:00". 30 Aug is a Monday but not in the first 7 days of a month.

public function testCheckNextDate()
{
    $data = [
        'cronexpression' => '0 0 1-7 * 1',
        'basedatetime' => '2021-08-25 00:00:00',
        'expectnext' => '2021-09-06 00:00:00',
    ];

    $cron = CronExpression::factory($data['cronexpression']);
    $next = $cron->getNextRunDate($data['basedatetime'])->format('Y-m-d H:i:s');
    assertSame($data['expectnext'], $next, $data['expectnext'] . '  !== ' . $next);
}

I have cron-expression 3.1 running on PHP 7.3 on a Windows 10 device.

I set the timezone in the Setup function. I have tried it with Australia/Sydney (my local) and America/Los_Angeles. The results are the same.

I have also tried '0 0 1,2,3,4,5,6,7 * 1' and '0 0 1-7 * Mon', which should produce similar results. They give the same incorrect answer.

**Comment by dragonmantank** [comment]
The expression actually translates to `At 00:00 on every day-of-month from 1 through 7 and on Monday.` The important thing to note (which isn't readily apparent) is that Day of Week and Day of Month combine their results when both are specified, which is how the original C implementation is designed. So given a test time of `'2021-08-25 00:00:00`, your next run time is `2021-08-30 00:00:00`, the next upcoming Monday.

So the important thing to note in the translation is the `and on Monday` ... so you will run every day of 1-7 of the month, _and all Mondays_. This trips up a lot of people.
