### ISSUE TITLE
CRON expression to execute only once

### ISSUE THREAD

**Issue by gpariya** [dragonmantank/cron-expression#127]
What is the best way to define the cron definition to execute only once and non-recurring job (not to repeat next time)

Say for example to execute only once at Nov 23, 2021, 11:11 AM

I am not sure how to define year in [cron expression generator](https://crontab.guru/)

**Comment by dragonmantank** [comment]
Most implementations don't support running just once as YEAR is not a standard field, a cron normally is something you want to schedule and run over-and-over based on a schedule. A very few do, but this one follows the C cronie implementation as closely as possible, which does not specify a year field.

Your best bet would be to use an expression like `11 11 23 11 *`, which translates to `11:11 Nov 23 on any day of the week` ... this will validate for that one day and time, and you would then need to remove the cron entry from wherever you store it.
