### ISSUE TITLE
Feature Request : Implement Iterator interface

### ISSUE THREAD

**Issue by crazytonyi** [dragonmantank/cron-expression#13]
This class seems to be a good fit for the Iterator interface, possibly the SeekableIterator interface. This would remove (or make redundant) the `getPreviousRunDate` and `getNextRunDate` methods, making the object easier to work with in a foreach context or other contexts where iterating through the datetime matches of the expression.

When it comes down to it, this class is really a special form of the existing  `DatePeriod` class, but accepting a cron expression instead of an ISO-8601 date interval expression, right? Should this be modeled more closely to that class (and the `DateInterval` class)?

**Comment by dragonmantank** [comment]
Thanks for the suggestion.

This class's primary function is to evaluate whether an expression is valid, and to return what the next (or previous) expected date was to be run. While it _can_ be used to generate a large amount of run dates, it is not do this to complement the DateInterval class.
