### ISSUE TITLE
Periodic start shift

### ISSUE THREAD

**Issue by bilik** [dragonmantank/cron-expression#135]
Why the crone string is not correct: 1/2 * * * *
When checked, the library marks it as invalid.

**Comment by dragonmantank** [comment]
When doing a step expression, you need to provide an actual range. Semantically, you cannot "step" over a single value.

Effectively the above expression is the same as `1 * * * *` as you are setting a range with one unit, and your step value won't go anywhere.

**Comment by bilik** [comment]
I understand, it's a common and used form in Linux, but I understand that 1-59 / 2 is more logical.
