### ISSUE TITLE
 Uncaught Error: Class 'Webmozart\Assert\Assert'

### ISSUE THREAD

**Issue by 2331892928** [dragonmantank/cron-expression#136]
Uncaught Error: Class 'Webmozart\Assert\Assert'

**Comment by peterlaws** [comment]
You need to download and put it in the same directory

**Comment by dragonmantank** [comment]
Did you install the library via [Composer](https://getcomposer.org/)? If not, please use the Composer package manager to download all the dependencies.

If you are still having issues, please feel free to re-open this issue.
