### ISSUE TITLE
expression like "0 8,20 ? * ?" parse failed

### ISSUE THREAD

**Issue by imdgr886** [dragonmantank/cron-expression#137]
but `CronExpression::isValidExpression("0 8,20 ? * ?")` is return `true`

**Comment by dragonmantank** [comment]
This is indeed a bug, the issue is the two parts don't reference each other so it doesn't throw an error. It should though an invalid expression error though.

**Comment by dragonmantank** [comment]
This should be fixed in the latest release (v3.3.3), let me know if you are still having problems.
