### ISSUE TITLE
Is it possible to schedule something every 14 days, and if so, is it possible to specify "starting from this day"?

### ISSUE THREAD

**Issue by simensen** [dragonmantank/cron-expression#147]
It seems like many cron expressions are specific to the implementation and it isn't clear to me if any of these things are possible with this specific library.

My end goal is wanting to create a cron expression that runs at 10:30am every 14 days (fortnightly), starting with Tuesday, September 13th. The human-readable form would be, "every other tuesday at 10:30am" but the "every other" should be based on a specific tuesday being the seed.

I feel like I've seen some implementations that let you specify "starting at", but I'm not sure if it was cron or something more like caldav for recurring events. :)

I figured the easiest thing (for me) to do would be to ask her if this is even remotely possible with this library before trying to hack a solution only to find out "nope, this wasn't ever going to be doable."

Thanks. :)

**Comment by dragonmantank** [comment]
Currently no, because the expression is just an arbitrary "every X amount of time", not "starting on X expression, run every X amount of time". The crontab expression would need a way to specify that starting date, so I'm not aware of any implementation that would work like that. Sorry :(
