### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by peterlaws** [dragonmantank/cron-expression#149]
Is it possible to install this without using composer? I just want to integrate (plugin) it into my own project so I can parse cron expressions from a database. Has anyone managed to do this?

**Comment by toniop99** [comment]
Hi! 

You can download de source code. (**Download zip**)
![Captura de Pantalla 2022-10-03 a las 19 23 25](https://user-images.githubusercontent.com/35426566/193640095-f7b8f44c-5666-4a0c-b956-cd5e84a5320e.png)

Then unzip it where you want in your project, and **require** the needed files into your project.

**Comment by peterlaws** [comment]
Wasn't sure if there were dependencies. which there is

```Webmozart\Assert\Assert```

Sorted now
