### ISSUE TITLE
DayOfMonthField : 'LW' option !?

### ISSUE THREAD

**Issue by tomitomas** [dragonmantank/cron-expression#151]
Hi Michael ! 

thanks for the repo, great job here ! 

I try to find out if I'm doing something wrong, or if the lib just doesn't handle the 'LW' combination option at the DayOfMonthField position. 

like `0 10 LW * *` stands for "At 10:00 AM, on the last weekday of the month"
but I've got an error "Uncaught Error: Call to a member function format() on bool in /var/www/html/vendor/dragonmantank/cron-expression/src/Cron/DayOfMonthField.php:51"

could you please confirm if LW works !?

**Comment by tomitomas** [comment]
Hi @dragonmantank 

any news please ? :)

**Comment by kendertas** [comment]
Hi, 

same for
0 10 * * MON#2
or
0 10 * * 2#2
that stands for "At 10:00 AM, on the second Monday of the month"

Thanks.
