### ISSUE TITLE
What is Due() for?

### ISSUE THREAD

**Issue by peterlaws** [dragonmantank/cron-expression#152]
Might be a stupid question.

Can someone explain what `$blah->Due()` is for...... I thought it was to check if a datetime = exactly now?
So if it's **not** 12 am on the 11th of November  (eg. before it) it would return **false**
eg.
`$blah = new Cron\CronExpression( 'blah ');`
`$blah->Due( '2022-11-11 00:00:00' );`
but it always returns **true**

Do we need to check ourselves if a datetime = exactly now?

**Comment by mwllgr** [comment]
Should work, here's the implementation of the method, I'm guessing that you mean `isDue()`: https://github.com/dragonmantank/cron-expression/blob/master/src/Cron/CronExpression.php#L389
