### ISSUE TITLE
why can't I require version 3.3.2 but only up to 3.3.1?

### ISSUE THREAD

**Issue by kisssg** [dragonmantank/cron-expression#153]
$ composer require dragonmantank/cron-expression:3.3.2
./composer.json has been updated
Running composer update dragonmantank/cron-expression
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dragonmantank/cron-expression 3.3.2, found dragonmantank/cron-expression[dev-set-up-semaphore, dev-update-v3-php8, dev-master, dev-issue/35-fix-and-or-problem, dev-allow-phpstan-failures, v1.0.0, ..., v1.2.1, v2.0.0, ..., v2.3.1.x-dev, v3.0.0, ..., v3.3.1] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content

**Comment by dragonmantank** [comment]
The tags all start with `v`, so you may want to try:

    composer require dragonmantank/cron-expression:v3.3.2

**Comment by kisssg** [comment]
> The tags all start with `v`, so you may want to try:
> 
> 
> 
>     composer require dragonmantank/cron-expression:v3.3.2

Thanks it's because I was using a mirror repository that didn't sync  timely
