### ISSUE TITLE
Invalid cron expression causes memory overflow

### ISSUE THREAD

**Issue by DKhalil** [dragonmantank/cron-expression#156]
The particular expression in our case was this:

```php
$cron = new \Cron\CronExpression('0 0 - 2,5,8,11 ?');
```

Just creating a new CronExpression object will cause an endless loop and run out of memory at some point.

Tested with v3.3.2

**Comment by dragonmantank** [comment]
Can you let me know what PHP version and OS you are using? That cron expression should immediately bail out with:

    InvalidArgumentException: Invalid CRON field value - at position 2

**Comment by DKhalil** [comment]
After trying it out now with 3.3.3 that is what happens, yes. Thanks!
