### ISSUE TITLE
Support for (optional) Seconds Field

### ISSUE THREAD

**Issue by rumpfc** [dragonmantank/cron-expression#166]
There are some use cases where cron tasks have to run more than once per minute. It might not be support for Linux crons, but frameworks with internal scheduling features (i.e. Java Spring Boot) support or require a Seconds field.

`10 5 * * *` (5 fields) would mean trigger every day at 05:10:00 am
`0 10 5 * * *` (6 fields) also means trigger every day at 05:10:00 am
`* 10 5 * * *` (6 fields) means trigger every day between 05:10:00 am and 05:10:59 am every second

6 field parsing should be optional for backwards compatibility.

**Comment by mabar** [comment]
And sometimes there is instead field for year. Or both. Compatibility nightmare. 
Also, crontab usually runs few seconds late and some jobs would never match. I've implemented simplified version of this feature outside of cron expression in [orisai/scheduler](https://github.com/orisai/scheduler/blob/84d09f8140069ce504e14edbffeac4363f38c02d/docs/README.md#seconds) to repeat job every few seconds.
Scheduler in Laravel also has the same feature, but it's coupled with the whole framework, not an independent library.

**Comment by dragonmantank** [comment]
@mabar mentioned, this is going to create a compatibility nightmare. `cron` itself is not designed to run with a per-second specificity, so this is not something the library should implement.

Thanks for the suggestion though!
