### ISSUE TITLE
Add optional support non standard cron ?

### ISSUE THREAD

**Issue by melicerte** [dragonmantank/cron-expression#169]
Hi,

First of all, thank you for your excellent work :)

I have a use case where I would like to use a non-standard cron expression.

For example: 5 7/4 * * *
https://crontab.guru/#5_7/4_*_*_*

This means: At minute 5 every 4 hours from 7 to 23.

My IOT code in C understands this expression, but I can't validate it on the PHP side.

Would it be possible to add support for this type of CRON expression, on an optional activation basis (with all the necessary warnings)?

**Comment by dragonmantank** [comment]
Unfortunately this breaks the syntax, so I wouldn't be comfortable making this change.

Is there a reason you cannot just change this to be `5 7-23/4 * * *`? By adding a valid range to the hour step, it's more compatible with all cron engines, not just this library.

**Comment by melicerte** [comment]
You're absolutely right, thanks for the answer, I'll use the standard syntax. No need to do otherwise.

**Comment by soulseekah** [comment]
https://stackoverflow.com/a/77615388/482864
