### ISSUE TITLE
Valid expression fails validation

### ISSUE THREAD

**Issue by kchapple** [dragonmantank/cron-expression#173]
This cron expression `1 4 1/2 * *` which should run at 04:01 AM, every 2 days causes an invalid argument exception.

Using version `v3.3.3`

php artisan tinker
```
Psy Shell v0.11.21 (PHP 8.1.4 — cli) by Justin Hileman
> // Works with predefined scheduling definitions
$cron = new Cron\CronExpression('1 4 1/2 * *');
$cron->isDue();
echo $cron->getNextRunDate()->format('Y-m-d H:i:s');
```

`InvalidArgumentException  Invalid CRON field value 1/2 at position 2.
`

**Comment by dragonmantank** [comment]
Yeah, `1/2` is a non-standard shorthand for `*/2` (which is a standard shorthand for `1-31/2`). So you would want to use either of the ones mentioned by @mabar

**Comment by kchapple** [comment]
Thanks guys, I thought it might be ok because this example is in the Oracle docs, but Chat GPT says it's non-standard, so it must not be, LOL. Maybe their implementation is non-standard. 

`0 0 12 1/5 * ? | Fire at 12 PM (noon) every 5 days every month, starting on the first day of the month`

https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm
