### ISSUE TITLE
0/5 * * * *  is throwing OutOfRangeException

### ISSUE THREAD

**Issue by tiggreen** [dragonmantank/cron-expression#18]
The factory should not accept this cron expression as valid because `getMultipleRunDates(X)` throws `OutOfRangeException` exception.

**Comment by dragonmantank** [comment]
I believe this was actually fixed with #45, and I added a regression test in b8d6872a13f02f4a7712acb30bfcd7289d2ba3ee. We should no longer accept `0/5` as a valid range.

Thanks for pointing this out!
