### ISSUE TITLE
behaviour on getPreviousRunDate/getNextRunDate

### ISSUE THREAD

**Issue by matteomarini-adam** [dragonmantank/cron-expression#185]
hello @dragonmantank 
I've recently update to the latest version but I notice some behaviuour changes. 
getPreviousRunDate now, If both day of month and day of week are set in an expression, return a date which among dates matching either of two criteria is closest to the current date and not check both criteria. 
I found a specific test for this case (testGetRunDateHandlesSimultaneousDayOfMonthAndDayOfWeek), but I don't undestand the reason for this change, since in Linux crontab the actual behaviour is launching the command if both criteria are met

These are my tests:

```php
 public function testDayAndMonthOnlyFewDayAWeek(){
    	$crontab_string = "30 14 31 12 1-5";
	$cron =  new CronExpression($crontab_string);
	/**  @var DateTime */
	$date_time = new DateTime();
	$date_time->setTimestamp(mktime(12,0,0,5,2,2024));
	$date_time->setTimezone(new DateTimeZone('Europe/Rome'));
	$previuous_day_datetime = $cron->getPreviousRunDate($date_time);
	// the expected result is 2021-12-31: 2023-12-31 was on sunday, but crontab-string it's only from mon-fri
	$this->assertSame('2021-12-31 14:30:00', date("Y-m-d H:i:s",$previuous_day_datetime->getTimestamp()));
    }
    
    public function testDayOfMonthOnlyFewDayAWeek(){
    	$crontab_string = "30 14 16 * 1-5";
	$cron =  new CronExpression($crontab_string);
	/**  @var DateTime */
	$date_time = new DateTime();
	$date_time->setTimestamp(mktime(12,0,0,5,2,2024));
	$date_time->setTimezone(new DateTimeZone('Europe/Rome'));
	$previuous_day_datetime = $cron->getPreviousRunDate($date_time);
	// the expected result is 2024-04-16: but getPreviousRunDate returns 2024-05-01
	$this->assertSame('2024-04-16 14:30:00', date("Y-m-d H:i:s",$previuous_day_datetime->getTimestamp()));
    }
``` 

Thank you for your work on this library

**Comment by dragonmantank** [comment]
This is actually a quirk of the POSIX standard:
https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/crontab.html

Technically, everything is an `AND` operation except if you pass both a DayOfWeek and DayOfMonth, that those two fields together become an `OR` operation. Some packages do not follow the posix standard and turn it into an `AND` operation.
