### ISSUE TITLE
Consider removing webmozart/assert as a production dependency

### ISSUE THREAD

**Issue by 8ctopus** [dragonmantank/cron-expression#186]
All in webmozart/assert is only used 4 times in `CronExpression.php`:
- 3 times to check if an object is an instance of a class
- once to check if a variable is an array

If you agree to the idea, I'll be happy to create a PR.

**Comment by dragonmantank** [comment]
Sounds good!

**Comment by dragonmantank** [comment]
Removed in v3.4
