### ISSUE TITLE
Hours issue with */n?

### ISSUE THREAD

**Issue by palsypentertainment** [dragonmantank/cron-expression#191]
Am I going mad here?

Say I have a cron of `* */6 * * *` (every 6 hours) and use `->getNextRunDate('* */6 * * *')->format('Y-m-d H:i:s')`, the hour is always set to 00.

I mean, if the current date/time is _2024-10-10 20:00_, I assume when you do `->getNextRunDate()` the next run would be _2024-10-11 02:00_?

**Comment by mabar** [comment]
It is every 6 hours. But it is the 0th, 6th, 12th, 18th hour of the day. Not just 6 hours from now, whatever that is.
