### ISSUE TITLE
Multiple steps not allow

### ISSUE THREAD

**Issue by jvrsolis** [dragonmantank/cron-expression#20]
It may be nothing but I thought you could include multiple step list items
Though not entirely useful in the below example it is still valid but fails the ->validate() function:
         */2,1-4/2  (past every 2nd hour and every 2nd hour from 1 through 4)
on any field but you can't

I think its still valid syntax that could be solved by moving the evaluation of each list item just below the early exit '*' but above the evaluation of the dash "/" in the validation function.

Let me know if I am not correct

**Comment by dragonmantank** [comment]
As far as I know, this is not standard syntax. If you can show where this syntax is valid via the cronie package, which this library tries to adhere to, or something close (vixie-cron or anacron) then I may reconsider. Feel free to re-open this issue with a daemon that supports this syntax. 

I believe in the 1.x line we did support this syntax, but with 2.x this library tries to stick very closely to stock cron implementations, especially cronie.
