### ISSUE TITLE
Symfony bundle

### ISSUE THREAD

**Issue by loevgaard** [dragonmantank/cron-expression#23]
Hi

And thanks for a great library. I couldn't find any well tested/up to date libraries integrating your library into Symfony, so I created one: [CronExpressionBundle](https://github.com/Setono/CronExpressionBundle) if you want to link to it somewhere in your docs.

Anyways, thanks!

**Comment by dragonmantank** [comment]
Thanks for this, I've added it to the README in a2c60195a4d8841a2a7811e3121c63ebd33aa1b0
