### ISSUE TITLE
Can't parse week days

### ISSUE THREAD

**Issue by nunoperalta** [dragonmantank/cron-expression#24]
This is a valid setting:

> 30 7 * * Mon

But, an exception is thrown:

> Uncaught InvalidArgumentException, code 0: Invalid CRON field value Mon at position 4
> Cron/CronExpression.php on line 154
> #0 Cron/CronExpression.php(136): Cron\CronExpression->setPart(4, 'Mon')
> #1 Cron/CronExpression.php(115): Cron\CronExpression->setExpression('30 7 * * Mon ')
> #2 Cron/CronExpression.php(84): Cron\CronExpression->__construct('30 7 * * Mon ', Object(Cron\FieldFactory))

**Comment by nunoperalta** [comment]
Hello,

That seems to work indeed :)

Thank you very much.

**Comment by kabengwa** [comment]
Not worked on this yet? because i am just using it now and its throwing the same error ... with the same problem and i can force the clients to use upper case ... they have an option to enter the cron they want in my system.

**Comment by SteenSchutt** [comment]
@kabengwa Is anything preventing you from just converting it to uppercase? `strtoupper($input)`
