### ISSUE TITLE
5 is not a valid position

### ISSUE THREAD

**Issue by arjayads** [dragonmantank/cron-expression#29]
CronExpression::factory('0 * * * * ? *') produces `5 is not a valid position`

**Comment by dragonmantank** [comment]
`0 * * * * ? *` is not a valid expression. There are only 5 positions that can be used (minutes, hours, day of month, month, day of week). Year support was dropped with version 2.0, and we've never supported anything higher than the year position. 

b195d12e3ebe73711c2f97ea651da711ff64cbc9 does change this to report the human readable position now though, so it's easier to determine which field caused the error.

**Comment by bs-thomas** [comment]
Thanks, your reply was just in time for me!  Just hit this error 5 minutes ago.

Thanks @dragonmantank !

Btw, just curious, why must year be dropped?

**Comment by dragonmantank** [comment]
I decided to have the library try and stick as close to real cron syntax as possible, and Year was an addition that is not standard. It was dropped when 2.0 was released, as where a few other non-standard elements. Right now I attempt to stick as close to the cronie syntax as possible, as it is one of the oldest and cleanest cron systems still in use.

It's also a very extreme edge case where you have to run things at intervals that are X years (for example, you can easily run something once every year by settings Month and Day settings).

**Comment by bs-thomas** [comment]
@dragonmantank Sounds fair!  And true about the rare edge case.  Thanks for the quick response man!
