### ISSUE TITLE
or/and bug

### ISSUE THREAD

**Issue by adminc** [dragonmantank/cron-expression#35]
I use the library in a script that monitors cronjobs. Now we have the issue that crond handle the expression in another way than the library predicted.

The expression is: 30 0 1 * 1 

Crond run on every monday and on every 1th of the month. Crond use OR. The library use AND. So the library thinks cron would only run when the 1th of the month is a monday.

Is it intentional that the library behaves like this or is it a bug?

**Comment by dragonmantank** [comment]
Which exact cron package does your system use, just for reference? `crond` can be packaged underneath as various systems (vixie-cron, cronie, and anacron are the most common).

I am finding some ambiguity with some cron packages, but most of them are saying this should be `00:30 on DOM 1, as well as on Monday`, so I can definitely look into this.

**Comment by adminc** [comment]
Oh sorry yes I forgot this information. We use Debian stable. In this case it is the Vixie Cron.

**Comment by dragonmantank** [comment]
Sorry for taking so long to circle back to this. The year has been a bit crazy.

I have a sample branch at `issue/35-fix-and-or-problem` if you want to take a look. I feel like it's a bit of a brute-force for the underlying issue, but with how we do the increment procedure which causes the issue, I don't want to change the behavior much. This is special behavior for only when both the Day of Week _and_ Day of Month are specified, so I think any solution is going to look weird.

If you can, try this branch out and see if it jives with what dates you are expecting. If you can, try and map out some dates in the future to test as well. The unit test has 5 next dates that match with another calculator, so I'm reasonably confident.

**Comment by dragonmantank** [comment]
@adminc Just wanted to follow up on this and see if you had a chance to test anything. If not, no big deal. I plan on doing a release by the end of the year to include this in the mainline code.

**Comment by dragonmantank** [comment]
This has been merged in, and will go out with v3.0.0 here soon.
