### ISSUE TITLE
Throw Exception on non-standard expression x/y

### ISSUE THREAD

**Issue by piotr-cz** [dragonmantank/cron-expression#44]
I've been using (mtdowling/cron-expression)[https://github.com/mtdowling/cron-expression] with expressions like `1/10 * * * *` to run processes every 10th minute with 1 minute offset (hh:01, hh:11, hh:21, hh:32, hh:41, hh:51).

Afer switching to this library, expression has been evaluated as due only once per hour at hh:01.

I fixed the problem by changing expression to `1-59/10 * * * *` however as there were no reports in error log, I had to debug whole application before finding out the cause of why data are not available.

It would be much easier to debug if this library would throw an exception on non standard expression to avoid false positives.

In this specific case, probably [AbstractField::validate](https://github.com/dragonmantank/cron-expression/blob/v2.3.0/src/Cron/AbstractField.php#L233) should throw an exception when there is range and step present and range is not in format (x-y).:

```php
if (strpos($value, '/') !== false) {
    list($range, $step) = explode('/', $value);

    // Don't allow numeric ranges
    if (is_numeric($range)) {
        return false;
    }

    return $this->validate($range) && filter_var($step, FILTER_VALIDATE_INT);
}
```

For reference, when testing ``1/10 * * * *`` in [crontab.guru](https://crontab.guru/#1/10_*_*_*_*) expression is evaluated as _“At every 10th minute from 1 through 59.”_, but there is a warning below: _Non standard! May not work with every cron._

**Comment by imyip** [comment]
But I think this expressions is very common and should not be banned.

**Comment by imyip** [comment]
But I think this expressions is very common and should not be banned.
