### ISSUE TITLE
which macros etc

### ISSUE THREAD

**Issue by ftrotter** [dragonmantank/cron-expression#46]
It is great that your project supports cron macros like @daily. But which ones are supported?

Seems like this should be covered in the readme.

Also I read your blog post, and it seems reasonable that you refer to the right place in cronie that your cron expression logic is now sourced from. 

If you agree that this welcome, I can submit a pull request with this "real soon now".

-FT

**Comment by dragonmantank** [comment]
Added this to the README with b80b95b094636e7661f60fbf85e5188c273f72b8.

Thanks for pointing this out!
