### ISSUE TITLE
InvalidArgumentException : Invalid CRON field value

### ISSUE THREAD

**Issue by smertius** [dragonmantank/cron-expression#7]
If I trying to parse example from readme file, I got Invalid  argument exception. 
I've used PHP 7.1 
```
// Works with complex expressions
$cron = Cron\CronExpression::factory('3-59/15 2,6-12 */15 1 2-5');
echo $cron->getNextRunDate()->format('Y-m-d H:i:s');

```

Result: 

`InvalidArgumentException : Invalid CRON field value 2,6-12 at position 1
`

**Comment by dragonmantank** [comment]
Thanks for catching this. The example in the README was valid for the old 1.x branch, but not for the new 2.x.

This was corrected in 2a88eac.
