### ISSUE TITLE
Cron for every X amount of hours is returning interesting results.

### ISSUE THREAD

**Issue by Elycin** [dragonmantank/cron-expression#72]
Hello,

While utilizing this library, I'm trying to work on an interface that allows a user to interface a specific interval for a cron task to run. I've potentially discovered this issue where the next run date appears to not be changing after 2 hours.

I am not sure if it is an actual issue with the library, or if there's some kind of rule I am forgetting about cron intervals itself.

Code Sample:
```php
\Cron\CronExpression::factory("0 */1 * * *")->getNextRunDate()->getTimestamp()
```

Example output when incrementing the hour:
![image](https://user-images.githubusercontent.com/33913289/75926539-90873a80-5e1f-11ea-811d-47074d4c4a00.png)

Could I please get some help?

Thanks,
Ely Haughie

**Comment by dragonmantank** [comment]
Hello! I haven't had a chance to double check this, but could you let me know why you closed this? I want to make sure it's not something simple I can help avoid in the future.

**Comment by Elycin** [comment]
Hi Chris,

After discussion with some friends we've concluded that this is accurate,
and that the timeframe was a multiple.
