### ISSUE TITLE
Human Readable cron String

### ISSUE THREAD

**Issue by paianoa** [dragonmantank/cron-expression#74]
FEATURE request:

It would be nice to have a method to translate cron string to a human readable format, like prettyCron js library (http://azza-bazoo.github.io/prettycron/). So for example:

Cron expression: 0 * * * *
Human readable: Every hour, on the hour

Cron expression: 30 * * * 1
Human readable: Every 30th minute past every hour on Mon

Cron expression: 15,45 9,21 * * *
Human readable: 09:15, 09:45, 21:15 and 21:45 every day

Cron expression: 18,19 7 5 * *
Human readable: 07:18 and 07:19 on the 5th of every month

Cron expression: * * 25 12 *
Human readable: Every minute on the 25th in Dec

Cron expression: 0 * 1,3 * *
Human readable: Every hour, on the hour on the 1 and 3rd of every month

Cron expression: 0 17 * 1,4,7,10 *
Human readable: 17:00 every day in Jan, Apr, Jul and Oct

**Comment by DerekCresswell** [comment]
Here is a PHP library for this https://github.com/lorisleiva/cron-translator

I'd love to provide a PR with an implementation of this. Add a couple helper methods to the current classes.

**Comment by Evoke-PHP** [comment]
I found a comment on a similar issue https://github.com/dragonmantank/cron-expression/issues/8#issuecomment-465607916 which I agree with. This library is beautiful because it is simple and keeps itself to a single concern.

**Comment by DerekCresswell** [comment]
@Evoke-PHP Yes that does make sense. I would still argue that having human readable cron is very essential to interacting with expressions. Any time you need to put in a string this could be used to ensure you understand exactly the schedule you are giving.

**Comment by dragonmantank** [comment]
As mentioned above, I feel that this is out of scope. There are other libraries like `cron-translator` above that already perform the job.

I wouldn't mind human readable -> cron expression, but there's no reason to duplicate effort here.
